package com.reportweb.service;

import com.reportweb.dto.ExportTextPreviewDTO;
import com.reportweb.dto.ProjectOverviewPreviewDTO;
import com.reportweb.entity.Project;
import com.reportweb.entity.Report;

import java.util.List;

/**
 * 项目 Word 生成（单项报告、总报告、第三方-only、技术监督检测通知单）。
 */
public interface WordGeneratorService {

    /**
     * 生成单个报告的 Word 文档（正式版式与项目总报告内单项相同：概述顺序、双轨编号同步、润电/第三方样式与白名单规则一致）。
     *
     * @param report 报告实体（须已关联项目并含 reportItems）
     * @return Word 文档的字节数组
     */
    byte[] generateReportAsync(Report report);

    /**
     * 生成项目总报告的 Word 文档
     *
     * @param project 项目实体
     * @return Word 文档的字节数组
     */
    byte[] generateProjectSummaryAsync(Project project);

    /**
     * 仅生成项目中第三方样式单项正文（与总报告中第三方段一致，无封面/概述）。
     *
     * @param project 项目实体
     * @return Word 文档的字节数组
     */
    byte[] generateThirdPartyOnlyProjectWordAsync(Project project);

    /**
     * 技术监督检测通知单：仅勾选且校验通过的缺陷单项，每页一份（可跨多个检测日期）。
     *
     * @param project   项目实体
     * @param reportIds 报告 ID 列表（不重复）
     * @return Word 文档的字节数组
     */
    byte[] generateTechnicalSupervisionNotifications(Project project, List<Integer> reportIds);

    /**
     * 将多条报告的正文按顺序合并为一个 Word（无封面、概述等总报告章节；版式与总报告内单项一致）。
     *
     * @param reportsInOrder 已排序的报告列表，每条须已加载 project、reportItems 等关联
     */
    byte[] generateMergedFormalReportsWord(List<Report> reportsInOrder);

    /**
     * 结论段落（忽略 {@code custom_fields._exportTextOverrides}），与单项 Word 自动生成一致。
     */
    String getConclusionTextAutoGenerated(Report report);

    /** 导出文字预览：自动生成默认值与已保存覆盖（默认第 0 段） */
    ExportTextPreviewDTO buildExportTextPreview(Report report);

    /** 按 detectionContent.rows 下标预览单项报告文案 */
    ExportTextPreviewDTO buildExportTextPreview(Report report, int contentRowIndex);

    /** 带项目上下文时概述编号与总报告 branding 子集一致 */
    ExportTextPreviewDTO buildExportTextPreview(Report report, int contentRowIndex, Project project);

    /**
     * 总报告摘要概述只读预览（类别/部件/条目与 Word 第 1～3 章一致；不持久化概述编号）。
     */
    ProjectOverviewPreviewDTO buildProjectOverviewPreview(Project project);
}